name: Deploy
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test

      - name: Deploy to Pinata
        uses: aquiladev/ipfs-action@master
        id: pinata
        with:
          path: ./packages/web-app/build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          key: ${{ secrets.IPNS_KEY }}
          pinName: L2Exit
          timeout: 3600
          verbose: true
